service: hotel-booking-api

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-north-1
  profile: ${env:AWS_PROFILE}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lambda:*"
        - "dynamodb:*"
        - "logs:*"
        - "apigateway:*"
      Resource: "*"
  role: arn:aws:iam::586794465159:role/bookingDevRole

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
